image: 
  - macOS
  - Visual Studio 2019
  
environment:
  matrix:
    #~ - PYTHON_HOME: "C:\\Python36"
      #~ PYTHON_VERSION: '3.6'
    #~ - PYTHON_HOME: "C:\\Python37"
      #~ PYTHON_VERSION: '3.7'
    - PYTHON_HOME: "C:\\Python38"
      PYTHON_VERSION: '3.8'
    - PYTHON_HOME: "C:\\Python39"
      PYTHON_VERSION: '3.9'

for:
  - 
    matrix:
      only:
        - image: Visual Studio 2019

    install:
      - "SET PATH=%PYTHON_HOME%;%PATH%"
      - "echo %PYTHON_HOME%"
      - "echo %PATH%"
      - "python --version"
      - "SET PATH=%PYTHON_HOME%;%PATH%"
      - "echo %PYTHON_HOME%"
      - "echo %PATH%"
      - "python -m pip install --upgrade setuptools wheel"
      - "python -m pip install --upgrade codecov coverage nose pillow pynput babel pytest"
  - 
    matrix:
      only:
        - image: macOS

    install:
      - sh: "brew install tcl-tk"
      - sh: "brew info tcl-tk"
      - sh: "source ~/venv${PYTHON_VERSION}/bin/activate"
      - sh: "python --version"
      - sh: "python -m pip install --upgrade setuptools wheel"
      - sh: "python -m pip install --upgrade codecov coverage nose pillow pynput babel pytest"

build: off
test_script:
    - "python -m pip install ."
    - "python -m nose --with-coverage"
after_test:
    - "python -m codecov"
